import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Eye, SlidersHorizontal } from 'lucide-react';
import ImageModal from './ImageModal';
import ComparisonSlider from './ComparisonSlider';

const Tile = ({ title, src, onOpen }) => <motion.article initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} className="overflow-hidden rounded-3xl border border-white/10 bg-slate-950/30 shadow-xl"><div className="flex items-center justify-between border-b border-white/10 px-5 py-3"><span className="text-sm font-bold">{title}</span><button onClick={() => onOpen(src, title)} className="text-slate-400 transition hover:text-white"><Eye size={16}/></button></div><button onClick={() => onOpen(src, title)} className="block aspect-[4/3] w-full overflow-hidden bg-slate-900/60"><img src={src} alt={title} className="h-full w-full object-cover transition duration-500 hover:scale-105"/></button></motion.article>;

function recolor(original, mask, opacity, color, threshold) {
  return new Promise(resolve => { const source = new Image(); const binary = new Image(); source.src = original; binary.src = mask; let loaded = 0; const ready = () => { if (++loaded !== 2) return; const canvas = document.createElement('canvas'); canvas.width = source.naturalWidth; canvas.height = source.naturalHeight; const context = canvas.getContext('2d'); context.drawImage(source, 0, 0); const base = context.getImageData(0, 0, canvas.width, canvas.height); const temp = document.createElement('canvas'); temp.width = canvas.width; temp.height = canvas.height; const maskContext = temp.getContext('2d'); maskContext.drawImage(binary, 0, 0, canvas.width, canvas.height); const pixels = maskContext.getImageData(0, 0, canvas.width, canvas.height).data; const rgb = color.match(/[a-f\d]{2}/gi).map(value => parseInt(value, 16)); for (let i=0; i<pixels.length; i+=4) if (pixels[i] >= threshold * 255) { base.data[i] = Math.round(base.data[i] * (1-opacity) + rgb[0] * opacity); base.data[i+1] = Math.round(base.data[i+1] * (1-opacity) + rgb[1] * opacity); base.data[i+2] = Math.round(base.data[i+2] * (1-opacity) + rgb[2] * opacity); } context.putImageData(base, 0, 0); resolve(canvas.toDataURL('image/png')); }; source.onload = ready; binary.onload = ready; });
}

export default function ComparisonView({ result, preview }) {
  const [opacity, setOpacity] = useState(.7); const [color, setColor] = useState('#ff6b3d'); const [threshold, setThreshold] = useState(.5); const [customOverlay, setCustomOverlay] = useState(result?.overlay); const [modal, setModal] = useState(); const original = result?.original || preview;
  useEffect(() => { let active = true; if (result?.mask && original) recolor(original, result.mask, opacity, color, threshold).then(image => active && setCustomOverlay(image)); return () => { active = false; }; }, [result?.mask, original, opacity, color, threshold]);
  const overlay = customOverlay || result?.overlay; const open = (src, title) => setModal({src, title});
  if (!result?.mask) return null;
  return <div className="mt-8"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-300">Prediction result</p><h3 className="mt-1 text-xl font-bold">Road network analysis</h3></div><span className="rounded-xl border border-orange-300/20 bg-orange-300/10 px-3 py-2 text-sm text-orange-100">Confidence <strong className="ml-1">{Math.round(result.confidence * 100)}%</strong></span></div><div className="grid gap-4 md:grid-cols-2"><Tile title="Original Image" src={original} onOpen={open}/><Tile title="Predicted Mask" src={result.mask} onOpen={open}/></div><div className="mt-4"><Tile title="Road Network Overlay" src={overlay} onOpen={open}/></div><section className="mt-5 rounded-3xl border border-white/10 bg-slate-950/25 p-5"><div className="mb-4 flex items-center gap-2"><SlidersHorizontal size={18} className="text-violet-300"/><h4 className="font-bold">Overlay controls</h4></div><div className="grid gap-5 md:grid-cols-3"><label className="text-sm text-slate-300">Opacity <span className="float-right text-violet-200">{Math.round(opacity*100)}%</span><input className="range" value={opacity} onChange={event=>setOpacity(Number(event.target.value))} min="0" max="1" step=".05" type="range"/></label><label className="text-sm text-slate-300">Mask threshold <span className="float-right text-violet-200">{threshold.toFixed(2)}</span><input className="range" value={threshold} onChange={event=>setThreshold(Number(event.target.value))} min="0" max="1" step=".05" type="range"/></label><label className="text-sm text-slate-300">Road color <span className="ml-2 inline-flex items-center gap-2"><input value={color} onChange={event=>setColor(event.target.value)} type="color" className="h-8 w-12 cursor-pointer rounded border-0 bg-transparent"/>{color}</span></label></div></section><ComparisonSlider original={original} overlay={overlay} onOpen={open}/>{modal && <ImageModal image={modal.src} title={modal.title} onClose={() => setModal(null)}/>}</div>;
}
