import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Maximize2, Minus, Plus, X } from 'lucide-react';

export default function ImageModal({ image, title, onClose }) {
  const [zoom, setZoom] = useState(1); const [position, setPosition] = useState({ x: 0, y: 0 });
  useEffect(() => { const close = (event) => event.key === 'Escape' && onClose(); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [onClose]);
  return <AnimatePresence><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose} className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/85 p-4 backdrop-blur-md"><motion.div initial={{ scale: .94, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: .94 }} onClick={event => event.stopPropagation()} className="glass relative w-full max-w-5xl overflow-hidden rounded-3xl"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><h3 className="font-bold">{title}</h3><div className="flex items-center gap-2"><button onClick={() => setZoom(Math.max(.5, zoom - .25))} className="modal-button"><Minus size={16}/></button><button onClick={() => { setZoom(1); setPosition({x:0,y:0}); }} className="modal-button"><Maximize2 size={16}/></button><button onClick={() => setZoom(Math.min(3, zoom + .25))} className="modal-button"><Plus size={16}/></button><button onClick={onClose} className="modal-button"><X size={17}/></button></div></div><div className="grid h-[70vh] place-items-center overflow-hidden bg-black/30"><motion.img drag dragElastic={.08} dragMomentum={false} src={image} alt={title} animate={{ scale: zoom, x: position.x, y: position.y }} onDragEnd={(_, info) => setPosition({x: position.x + info.offset.x, y: position.y + info.offset.y})} className="max-h-full max-w-full cursor-grab object-contain active:cursor-grabbing"/></div></motion.div></motion.div></AnimatePresence>;
}
